### ISSUE TITLE
PWA features

### ISSUE THREAD

**Issue by gaboesquivel** [puravidadac/dmeetup#24]
Research and identify PWA features we potentially want to use/support in the DApp

**Comment by dfernandeza** [comment]
Hello,
Suggested list of features:

- Service Worker to cache static files
- Background sync to support user actions when offline (vote, comment) 
- Cache data (indexedBD) so the user can still see (stale) data when offline, we can cache things like calendar, past events data, etc so the app is still useful

[Workbox](https://developers.google.com/web/tools/workbox/) has good support for above features however, we would need to integrate workbox config into react-app-rewired, to accomplish this we will need something similar to this approach:

https://github.com/davejm/react-app-rewire-workbox/blob/master/index.js

cheers

**Comment by kevin-wolf** [comment]
`create-react-app` [supports PWAs](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/template#making-a-progressive-web-app) out-of-the-box I think the only work needed here is to tweak the `public/index.html` and `public/manifest.json` files.

**Comment by dfernandeza** [comment]
The thing is that CRA uses sw-precache-webpack-plugin to cache static files which is only one of the features I mentioned before, if we want to extend functionality to support the other 2 features we would need either to implement our own approach or use a tool like workbox, but it actually depends on what features we would like to support.

cheers

**Comment by gaboesquivel** [comment]
React Native and React Native Web instead
