### ISSUE TITLE
UX Specs Document

### ISSUE THREAD

**Issue by murillojorge** [puravidadac/dmeetup#56]
We've prepared a document with a preliminary set of UX Specs. Please leave comments and as soon as we come to the conclusion that this is the road we want to take, I'll make a PR in order to add it to the project documentation.

https://docs.google.com/document/d/1AUGaSm3LHrTXQqc0RPh-plDjh0yHRWkAjx4TbGKrWLQ/edit?usp=sharing 

Feel free to comment, everything is valued.

**Comment by gaboesquivel** [comment]
We agreed on this during the call, I think we can now close it

**Comment by gaboesquivel** [comment]
included summary in the README file
